### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by lxlhum** [apebook/apebook#12]
我是一个node的初学者，对于gitbook很感兴趣。
不久前，我在github上看到了您开发的apebook，我被他的风格和理念深深的吸引住了，于是，我准备从源码层级深刻的学习apebook。
不过，因为我是一个菜鸟的原因，我有很多疑惑，想在这里跟您请教一下，感谢：

1.源码没有提供./bin这个文件夹，我看到app.js提供了module.exports = app;这种中间件的表达方式，那是不是您自己的正式项目中，已经写了./bin文件夹下的启动代码了....
2.app.js中的第一行：var _ = require('./base/util');是不是没有用到呀，还是相关代码没有提交，我没有找到在app.js中使用这部分功能的代码。

期待您的回复。

**Comment by minghe** [comment]
不需要 ./bin 目录，启动直接通过 node app.js 启动的

**Comment by minghe** [comment]
var _ = require('./base/util'); 是多余的引用，感谢提醒，我会删掉
